name: Custom Action Workflow
on:
  workflow_dispatch:
      inputs:
        first_name:
          description: 'First name of the user'
          required: true
jobs:
  custom-action-job:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout the branch
        uses: actions/checkout@v4.4.0 # you must do  this step before using the custom action
      - name: Run custom action
        uses: .github/customactions/greeting@v1
        with:
          first_name: ${{ inputs.first_name }}