name: workflow on Jobs
on: 
  workflow_dispatch:


jobs:
  job1:
    runs-on: ubuntu-22.04

    steps:
      - name: Print hello message
        run: echo "hello this is my workflow on ${{github.job}}"
  job2:
    runs-on: ubuntu-22.04
    needs: job1
    steps:
      - name: Print hello message
        run: echo "hello this is my workflow on ${{github.job}}"
  job3:
    runs-on: ubuntu-22.04
    needs: job1
    steps:
      - name: Print hello message
        run: echo "hello this is my workflow on ${{github.job}}"
  job4:
    runs-on: ubuntu-22.04
    needs: [job2, job3]
    steps:
      - name: Print hello message
        run: |
          echo "hello this is my workflow on ${{github.job}}"
          echo "I will be good"
        working-directory: /temp 
        shell: bash #cmd pwsh 
        