name: my first workflow
on:
  push: 
    branches:
      - main
jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: print first weclome message
        run: echo " hello from my first workflow"
      - name: clone the new version of 
        uses: actions/checkout@v7.0.0
      - name: list all objects in the repo
        run: ls -al
        
        
        
