name: my second workflow

on:
  push:
    branches:
      - main 
jobs:
  first-job:
   runs-on: ubuntu-22.04
   steps:
     - name: print hellp message 
       run: echo " hello this my first workflow"
       
  
