name: Manual Workflow
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - dev
          - staging
          - production
      


jobs:
  manual-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Print hello message
        run: echo "hello this is my manual workflow"  