name: Manual Workflow
on:
  workflow_dispatch:
      


jobs:
  manual-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Print hello message
        run: echo "hello this is my manual workflow"  