name: Push Pull Trigger

on:
  push:
    branches:
      - main
      - "release/*"
    paths:
      - "src/**"
      - "release/**"

  pull_request:
    branches:
      - main
      - "release/*"
    paths:
      - "src/**"
      - "release/**"

jobs:
  first-job:
  
    runs-on: ubuntu-22.04

    steps:
      - name: Run tests
        run: npm test