name: trigger workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *' # every 5 minutes

jobs:
  scheduled-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Print hello message
        run: echo "hello this is my scheduled workflow"