name: trigger workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5* * * *'

jobs:
  scheduled-job:
    runs-on: ubuntu-22.04

    steps:
      - name: Print hello message
        run: echo "hello this is my scheduled workflow"