name: workflow_commands 
on:
  workflow_dispatch
jobs:
  warning-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
               echo "::warning::take care there is an warning"
               echo " api_key=12345" >> $GITHUB_ENV
      - run: echo "${{$api_key}}"
